config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: %i[new create]
    resources :reviews, only: %i[new create]
  end
  resources :doses, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true, allow_blank: false

  def cocktail_average_review
    reviews_array = []
    reviews.each { |review| reviews_array << review.rating }
    if reviews.any?
      reviews_array.sum / reviews_array.size
    end
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :cocktail
  validates :description, presence: true
  STARS = [0, 1, 2, 3, 4, 5].freeze
  validates :rating, presence: true, numericality: true, inclusion: { in: STARS}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[show edit update destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: %i[new create]
  def new
      @dose = Dose.new
    end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

    def destroy
      @dose = Dose.find(params[:id])
      @cocktail = @dose.cocktail
      @dose.destroy
      redirect_to cocktail_path(@cocktail)
    end

    private

    def set_dose
      @cocktail = Cocktail.find(params[:cocktail_id])
    end

    def dose_params
      params.require(:dose).permit(:description, :ingredient_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
      @review = Review.new
      @cocktail = Cocktail.find(params[:cocktail_id])
    end

    def create
      @review = Review.new(review_params)
      @cocktail = Cocktail.find(params[:cocktail_id])
      @review.cocktail = @cocktail

      if @review.save
        redirect_to cocktail_path(@cocktail)
      else
        render "new"
      end
    end

    def destroy
        @review = Review.find(params[:id])
        @cocktail = @review.cocktail
        @review.destroy
        redirect_to cocktail_path(@cocktail)
      end

    private

    def review_params
      params.require(:review).permit(:description, :rating, :cocktail_id)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<div class="d-flex">
  <div class="background-show"></div>
  <%= link_to cocktails_path do %>
  <i class="fas fa-arrow-circle-left arrow"></i>
  <% end %>
  <div class="background-black">
      <div>
          <%= simple_form_for @cocktail do |f| %>
          <%= f.input :name %>
          <%= f.submit class: "button-new text-center w-100" %>
          <% end %>
      </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="banner">
    <%= image_tag "logo.png", class: "logo" %>
</div>
<div class="back-black">
    <div class="container d-flex justify-content-between align-items-center pt-5">
        <h3 class="cocktail-title">COCKTAILS</h3>
        <%= link_to new_cocktail_path do %>
        <i class="fas fa-plus"></i>
        <% end %>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <% @cocktails.each do |cocktail| %>
            <%= link_to cocktail_path(cocktail) do %>
            <div class="col-lg-3 col-md-5 box-cocktail m-2 mt-5">

                <% if cocktail.photo.attached? %>
                <div class="image-user mt-5"
                    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key %>')">
                </div>
                <% else %>
                <div class="card-image mt-5"></div>
                <% end %>

                <div class=" d-flex flex-column card-cocktail py-5">
                    <strong class="cocktail-title"><%= cocktail.name %></strong>
                    <% if cocktail.reviews.any? %>
                    <div>
                        <% cocktail.cocktail_average_review.times do %>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <% end %>
                    </div>
                    <% end %>

                </div>
                <% end %>
            </div>
            <% end %>
        </div>
    </div>
    <footer class="d-flex justify-content-around py-5">
        <ul class="p-0 d-inline-flex">
            <li><i class="fab fa-facebook-square pr-4"></i></li>
            <li><i class="fab fa-instagram pr-4"></i></li>
            <li><i class="fab fa-twitter"></i></li>
        </ul>
    </footer>
</div>

app/views/cocktails/new.html.erb
<div class="d-flex">
    <div class="background-show"></div>
    <%= link_to cocktails_path do %>
    <i class="fas fa-arrow-circle-left arrow"></i>
    <% end %>
    <div class="background-black">
        <div>
            <%= simple_form_for @cocktail do |f| %>
            <%= f.input :name %>
            <%= f.input :photo, as: :file %>
            <%= f.submit class: "button-new text-center w-100" %>
            <% end %>
        </div>
    </div>
</div>

app/views/cocktails/show.html.erb
<div class="d-flex">
    <% if @cocktail.photo.attached? %>
    <div class="background-user-image" style="background-image: linear-gradient(
      rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 5)), url('<%= cl_image_path @cocktail.photo.key, crop: :fill %>')"></div>
    <% else %>
    <div class="background-show"></div>
    <% end %>
    <div>
        <%= link_to cocktails_path do %>
        <i class="fas fa-arrow-circle-left arrow"></i>
        <% end %>
    </div>
    <div class="background-black">
        <div>
            <div class="d-flex w-100">
                <h3 class="cocktail-title"><%= @cocktail.name %></h3>
                <div class="d-flex flex-row justify-content-end">
                    <%= link_to edit_cocktail_path(@cocktail) do %>
                    <i class="fas fa-pencil-alt pr-3"></i>
                    <% end %>
                    <%= link_to cocktail_path(@cocktail), method: :delete, data: {confirm: "Are you sure?"} do %>
                    <i class="fas fa-trash"></i>
                    <% end %>
                </div>
            </div>
            <div class="col">
                <% @cocktail.doses.each do |dose| %>
                <div class="row justify-content-between">
                    <p> <%= dose.ingredient.name %> - <%= dose.description %></p>
                    <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                    <i class="fas fa-times"></i>
                    <% end %>
                </div>
                <% end %>
            </div>
            <div class="d-flex justify-content-center mt-5 border-top text-buttons">
                <%= link_to 'add dose', new_cocktail_dose_path(@cocktail), class: "px-3"%>
                <%= link_to 'add a review', new_cocktail_review_path(@cocktail)  %>
            </div>
            <% if @cocktail.reviews.count > 0 %>
            <ul class="d-flex flex-column w-100">
                <h3 class="cocktail-title mt-5"><%= "Reviews" %></h3>
                <% reviews = @cocktail.reviews  %>
                <% reviews.each do |review|  %>
                <li class="list-inline single-review mt-4">
                    <div class="d-flex flex-row justify-content-between align-items-center">
                        <div class="d-flex flex-column">
                            <%= review.description  %>
                            <div class="d-flex flex-row">
                                <% review.rating.times do  %>
                                <i class="fa fa-star pt-2" aria-hidden="true"></i>
                                <% end  %>
                            </div>
                        </div>
                        <%= link_to review_path(review), method: :delete, data: { confirm: "Are you sure?" } do %>
                        <i class="fas fa-trash"></i>
                        <% end %>
                        <% end %>
                        <% end %>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/doses/new.html.erb
<h3>Add a new dose</h3>
<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="d-flex">
  <div class="background-show"></div>
  <%= link_to cocktails_path do %>
  <i class="fas fa-arrow-circle-left arrow"></i>
  <% end %>
  <div class="background-black">
    <div>
      <%= simple_form_for [ @cocktail, @review ] do |f| %>
      <%= f.input :description %>
      <%= f.input :rating, collection: Review::STARS %>
      <%= f.submit "Submit review", class: " w-100 button-new" %>
      <% end %>
    </div>
  </div>
</div>